// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/ovo-sgw/internal/api"
	"github.com/liuzhaomax/ovo-sgw/internal/core"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware/auth"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware/reverse_proxy"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware/tracing"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware/validator"
	"github.com/liuzhaomax/ovo-sgw/internal/middleware_rpc"
	auth2 "github.com/liuzhaomax/ovo-sgw/internal/middleware_rpc/auth"
	tracing2 "github.com/liuzhaomax/ovo-sgw/internal/middleware_rpc/tracing"
	validator2 "github.com/liuzhaomax/ovo-sgw/internal/middleware_rpc/validator"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	engine := core.InitGinEngine()
	logger := core.InitLogrus()
	coreLogger := &core.Logger{
		Logger: logger,
	}
	client, cleanup, err := core.InitRedis()
	if err != nil {
		return nil, nil, err
	}
	authAuth := &auth.Auth{
		Logger: coreLogger,
		Redis:  client,
	}
	validatorValidator := &validator.Validator{
		Logger: coreLogger,
		Redis:  client,
	}
	configuration := core.InitTracer()
	tracingTracing := &tracing.Tracing{
		Logger:       coreLogger,
		TracerConfig: configuration,
	}
	reverseProxy := &reverse_proxy.ReverseProxy{
		Logger:      coreLogger,
		RedisClient: client,
	}
	middlewareMiddleware := &middleware.Middleware{
		Auth:         authAuth,
		Validator:    validatorValidator,
		Tracing:      tracingTracing,
		ReverseProxy: reverseProxy,
	}
	registry := core.InitPrometheusRegistry()
	handler := &api.Handler{
		Middleware:         middlewareMiddleware,
		PrometheusRegistry: registry,
	}
	db, cleanup2, err := core.InitDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	injectorHTTP := InjectorHTTP{
		Engine:  engine,
		Handler: handler,
		DB:      db,
		Redis:   client,
	}
	authRPC := &auth2.AuthRPC{
		Logger: coreLogger,
		Redis:  client,
	}
	validatorRPC := &validator2.ValidatorRPC{
		Logger: coreLogger,
		Redis:  client,
	}
	tracingRPC := &tracing2.TracingRPC{
		Logger:       coreLogger,
		TracerConfig: configuration,
	}
	middlewareRPC := &middleware_rpc.MiddlewareRPC{
		AuthRPC:      authRPC,
		ValidatorRPC: validatorRPC,
		TracingRPC:   tracingRPC,
	}
	handlerRPC := &api.HandlerRPC{
		PrometheusRegistry: registry,
		MiddlewareRPC:      middlewareRPC,
	}
	injectorRPC := InjectorRPC{
		HandlerRPC: handlerRPC,
		DB:         db,
		Redis:      client,
	}
	injector := &Injector{
		InjectorHTTP: injectorHTTP,
		InjectorRPC:  injectorRPC,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
